### ISSUE TITLE
Patient Details (for all modules)

### ISSUE THREAD

**Issue by machariamuguku** [opensrp/miecd#15]
references:
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p18
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p19

- [x] What will the previous pregnancies be displayed as? Is it going to Pregnancy 1, 2, 3 based on Gradivity submitted. So if Grad = 3 then it is Pregnancy 3.
- [x] Give more space for this column since it displays large amount of data
- [x] One line of report (single SMS) in patient file for multiple SMS submissions (as shown in logface for same ID)
- [x] Received SMSs should be displayed from from Newest to Oldest (same for all other patient files)
- [x] Location should be Village, Commune, District, Province
- [x] Please confirm how the reports (for the same pregnancy) will be ordered? Will it be based on date received or date of event? Will it be newest --> oldest
- [x] This basic information section does not include all information as required in the requirement document. Same for both mother's and child's.
- [x] The text should be: Month/Year: xx kg (change registered). For example: December/2019: 78 kg (+5)
- [x] For newborn + nutrition, there should be a reference line based on WHO growth chart
- [x] A graph on blood pressure should be added for mother profile.

**Comment by machariamuguku** [comment]
> - What will the previous pregnancies be displayed as? Is it going to Pregnancy 1, 2, 3 based on Gradivity submitted. So if Grad = 3 then it is Pregnancy 3.
> - Please confirm how the reports (for the same pregnancy) will be ordered? Will it be based on date received or date of event? Will it be newest --> oldest

@ageryck @p-netm clarification on above

**Comment by ageryck** [comment]
Please confirm how the reports (for the same pregnancy) will be ordered? Will it be based on date received or date of event? Will it be newest --> oldest

 - This concerns the identification messages sent for the same pregnancy, it should be ordered from newest to oldest and the order based on event dates (when the events are posted to OpenSRP successfully)

**Comment by peterMuriuki** [comment]
>     * Please confirm how the reports (for the same pregnancy) will be ordered? Will it be based on date received or date of event? Will it be newest --> oldest

newest to old by event date

**Comment by peterMuriuki** [comment]
>     * What will the previous pregnancies be displayed as? Is it going to Pregnancy 1, 2, 3 based on Gradivity submitted. So if Grad = 3 then it is Pregnancy 3.

current pregnancy
pregnancy 2
pregnancy 1
