### ISSUE TITLE
CORS Issue [webapp]

### ISSUE THREAD

**Issue by machariamuguku** [opensrp/miecd#16]
- [ ] CORS issue
- To be fixed by the backend deployment

**Comment by machariamuguku** [comment]
~~@ageryck @p-netm clarification on above~~

**Comment by ageryck** [comment]
~~@p-netm @HusnaHariz do you know exactly what cross-origin resource sharing issue Hilda documented~~

**Comment by peterMuriuki** [comment]
fixed by deploying discover as a subdomain of .smartregistore.org
