### ISSUE TITLE
compartment detail view(tabular) for all modules

### ISSUE THREAD

**Issue by machariamuguku** [opensrp/miecd#18]
references: 
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p12
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p13
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p14
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p15
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p16

- [x] Total number does not change as you drill down (province->district->commune->village)
- [x] Change drill down titles (Province/District/Commune/Village) to actual names.
- [x] Bold and make the letter size of Total row bigger
- [x] put a space between Total and (location). e.g in Total(Village)
- [x] newborn should not appear in the compartments for Mothers or vice versa (based on the document "Logface display")
- [x] change "selected commune" title to actual commune name (Apply for all Patient log)
- [x] At final level of disaggregation (drill down), change village names to black so users understand they are not clickable. maybe cursor: pointer for clickable and cursor: default/auto for not clickable?
- [x] Patient log for NBC (newborn) incorrectly titled as mothers in PNC.
- [x] Newborn tabular view header shows wrong total
- [ ] Newborn tabular view drill down for the following paths broken (no village table):

1. Gia Lai -> Mang Yang -> Ayun
2. Gia Lai -> Kbang -> Sơn Lang
3. Kon Tum -> Kon Rẫy -> Thị trấn Đắk Rve

- [ ] Newborn tabular view drill down for Điện Biên has only 1 district/1 Commune/1 village. 
- [ ] Newborn tabular view drill down for Kon Tum -> Kon Rẫy -> Tân Lập only 1 village shown

- [x] Patient log for view drill down is not in accordance to the requirement document. It should be: 

- Patient ID
- Age
- Location of residence (Village)
- Current Symptoms
- Previous risks/Existing medical conditions
- EDD
- Planned delivery location
- Risk categorization

**Comment by machariamuguku** [comment]
> - newborn should not appear in the compartments for Mothers or vice versa (based on the document "Logface display")
> - change "selected commune" title to actual commune name (Apply for all Patient log)

@ageryck @p-netm clarification on above

**Comment by ageryck** [comment]
change "selected commune" title to actual commune name (Apply for all Patient log)
- This should be specific to selected commune rather than as currently displayed in a generic way.
- Selected Province/Selected  District/Selected  Commune names and not  Province/District/Commune/Village

**Comment by ageryck** [comment]
newborn should not appear in the compartments for Mothers or vice versa (based on the document "Logface display")
- This is to keep both statistics clear of each other and to accurately represent them as described [here](https://docs.google.com/document/d/12jgr05r6ZBIRrZIPmXUBD0C9v7Ywtbj6/edit#heading=h.2et92p0)

**Comment by machariamuguku** [comment]
@ageryck @ukanga 

1. From [openSRP data](https://opensrp-miecd-stage.smartregister.org/opensrp/security/authenticate):

- The Ayun, Sơn Lang, and Thị trấn Đắk Rve communes have no villages.
- Điện Biên province has only: 1 district/1 Commune/1 village.
- Tân Lập commune has only one village (Thôn_1)

2. Location Of Residence, Location of birth, and Planned Delivery Location are not available in the sms data slice from superset (to be addressed in next iteration)
