### ISSUE TITLE
Login Credentials view

### ISSUE THREAD

**Issue by peterMuriuki** [opensrp/miecd#6]
references:
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p3
https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p4

- [ ] make logos smaller
- [ ] Add space between the two logos on authentication page
- [ ] The logo in the background should be seen in full, not partly covered by the photo

This view is not being served from the web app, changes might have to be made on the miecd opensrp repo.

**Comment by machariamuguku** [comment]
Closing in favour of moving to keycloak #5
