### ISSUE TITLE
Dashboards Home page

### ISSUE THREAD

**Issue by peterMuriuki** [opensrp/miecd#7]
reference : https://docs.google.com/presentation/d/1UJIhM-JRrLuSAvsiC-wZEpvy6SA8tPCG/edit#slide=id.p5

- [ ] Use actual photos to replace the cartoons.([new photos](https://drive.google.com/drive/u/1/folders/128ahNu0YFbkR8ylf1YqqH47xCgqqsrn-))

**Comment by machariamuguku** [comment]
~~@ageryck We need access to these photos~~
