### ISSUE TITLE
Regression in User details endpoint

### ISSUE THREAD

**Issue by peterMuriuki** [opensrp/miecd#8]
the api response from this url is now malformed:
https://opensrp-miecd-stage.smartregister.org/opensrp/user-details
the username field prop in the response  is named `userName`  but should be `username`. 

tools created to help parse such data and generally handle authentication expect that this field is called `username`

This issue is blocking logging in.

**Comment by moshthepitt** [comment]
@p-netm could you also raise this with the OpenSRP server team?  The MIECD server may need an upgrade or something.

**Comment by ndegwamartin** [comment]
Looks like this server hasn't been used in a while. This would be a great opportunity to move his deployment to Kubernetes. This is probably dependent on the project's timelines.

**Comment by ageryck** [comment]
@bennsimon do update us on how this is progressing. cc @p-netm
